#!/usr/bin/env python3
"""Build client/kiosk/index.html from kiosk-src/ as ONE self-contained file.

Why one file: clients up to 1.1.5 only copy screen_client.py and
kiosk/index.html during OTA, so the first 2.x kiosk must not depend on
any other file. Inline scripts are allowed by SHA-256 in the CSP, not by
'unsafe-inline'.

  python3 tools/build_kiosk.py          # write
  python3 tools/build_kiosk.py --check  # CI: fail if stale
"""
import base64, hashlib, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "kiosk-src"
OUT = ROOT / "client" / "kiosk" / "index.html"


def h(s):
    return "'sha256-" + base64.b64encode(hashlib.sha256(s.encode()).digest()).decode() + "'"


def version():
    return (ROOT / "client" / "VERSION").read_text().strip()


def build():
    css = (SRC / "player.css").read_text()
    # The player's version is injected here so it can never drift from
    # client/VERSION (it did: the pairing screen showed 2.0.6 on a 2.0.7 build).
    boot = "window.CHX_TRANSPORT='local';window.CHX_VERSION='%s';" % version()
    resolver = (SRC / "resolver.js").read_text()
    player = (SRC / "player.js").read_text()
    scripts = [boot, resolver, player]
    csp = ("default-src 'none'; script-src " + " ".join(h(x) for x in scripts) +
           "; style-src 'unsafe-inline'; img-src 'self' https: data:; media-src 'self'; connect-src 'self'; "
           "frame-src https:; base-uri 'none'; form-action 'none'")
    body = "\n".join("<script>%s</script>" % x for x in scripts)
    return f"""<!doctype html>
<!-- GENERATED by tools/build_kiosk.py from kiosk-src/. Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="referrer" content="no-referrer">
<meta http-equiv="Content-Security-Policy" content="{csp}">
<title>CrewHex screen</title>
<style>{css}</style>
</head>
<body>
<div id="root"></div>
<div id="banner"></div>
<div id="ident"><div></div></div>
<div id="net" role="status"><span></span></div>
{body}
</body>
</html>
"""


if __name__ == "__main__":
    html = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != html:
            sys.exit("client/kiosk/index.html is stale - run python3 tools/build_kiosk.py")
        print("kiosk up to date (v%s)" % version())
    else:
        OUT.write_text(html)
        print("wrote", OUT.relative_to(ROOT), len(html), "bytes")
